#!/usr/bin/env node
"use strict";

const path = require("path");
const { OIDeckBuilder, parseArgs } = require("../../oi_shapes"); // builder + diagram methods

const BASE = __dirname;
const cliOpts = parseArgs();
const OUTPUT = cliOpts.output ?? path.join(BASE, "TreeModelsDemo.pptx");
const CACHE_DIR = cliOpts.cacheDir ?? path.join(BASE, ".pptx_cache");

const deck = new OIDeckBuilder({
  figDir: cliOpts.figDir ?? path.join(BASE, "figures"),
  output: OUTPUT,
  cacheDir: CACHE_DIR,
  stylePreset: "guide2025",
  theme: { subtitleBar: { y: 0.74 } }, // edits/example_2026-07-09_raj_email.yaml e2
});
deck.figspecDir = path.join(BASE, "..", "..", "figspecs");

async function main() {
  deck.addTitleSlide(
    "Tree-Based Machine Learning Methods",
    "A Visual Introduction",
    "July 2026",
    "DEMO DECK — GENERATED BY oi-slide-v2"
  );

  deck.addRichTextSlide("Why Tree-Based Models?", [
    "Flexible prediction without assuming a functional form",
    ["Splits are learned from the data, not specified by the researcher", 1],
    ["Naturally capture interactions and nonlinearities", 1],
    "",
    "Two workhorses we use",
    ["Regression trees: one tree, easy to read and explain", 1],
    ["Gradient boosting: many small trees, state-of-the-art accuracy (small)", 1],
  ], { subtitle: "Motivation" });

  deck.addDiagramSlide(
    "A Regression Tree Splits the Data Into Groups",
    "Illustrative example: predicting a child's adult income",
    "regression_tree"
  );

  deck.addDiagramSlide(
    "Gradient Boosting Adds Trees That Fix Each Other's Mistakes",
    "Sequential ensemble of shallow trees",
    "gradient_boosting"
  );

  deck.addRichTextSlide("Practical Notes", [
    "1. Depth controls flexibility: shallow trees underfit, deep trees overfit",
    "2. Boosting hyperparameters: number of trees, depth, learning rate η",
    "3. Validate out-of-sample; report R² or RMSE next to OLS baselines",
    "",
    "All shapes on the diagram slides are native PowerPoint objects — open and edit them directly (small)",
  ]);

  await deck.save();
}

main().catch((err) => { console.error("Build failed:", err); process.exit(1); });
