#!/usr/bin/env node
"use strict";

// GENERATED by scripts/outline_to_deck.js from outline.md — do not hand-edit.
// Re-run:  npm run pipeline decks/tstc_oct2026

const path = require("path");
const { OIDeckBuilder, parseArgs } = require("../../oi_deck_builder");

const BASE = __dirname;
const cliOpts = parseArgs();
const FIG_DIR   = cliOpts.figDir   ?? "C:\\Users\\realj\\Opportunity Insights Dropbox\\Opportunity Insights Shared Workspace\\Research files\\outside\\workforce_training\\Slides\\TSTC_oct2026\\figures";
const OUTPUT    = cliOpts.output   ?? path.join(BASE, "TSTC_deck.pptx");
const CACHE_DIR = cliOpts.cacheDir ?? path.join(BASE, ".pptx_cache");

const deck = new OIDeckBuilder({
  figDir: FIG_DIR,
  output: OUTPUT,
  cacheDir: CACHE_DIR,
});

const fig = (name) => deck.fig(name);

async function main() {

  // --- line 17: TITLE SLIDE: The Impacts of TSTC Programs on Earnings
  deck.addTitleSlide("The Impacts of TSTC Programs on Earnings", "Preliminary Estimates Using Digital Twins", "October 2026", "PRELIMINARY DATA -- DO NOT CITE");

  // --- line 19: TABLE: TSTC Programs
  deck.addTableSlide("TSTC Programs", [
    ["School", "Division", "Example Program"],
    ["Business, Hospitality, and Global Trade", "Management Careers", "Human Resources Assistant"],
    ["Health Sciences", "Nursing", "Associate Degree Nursing"],
    ["Law and Public Service", "Criminal Justice", "Basic Criminal Justice Studies"],
    ["Engineering, Technology, Math & Science", "Computer Information Systems", "Technology Support"],
    ["Manufacturing and Industrial Technology", "Automotive Technology", "Automotive Repair"],
    ["Creative Arts, Entertainment & Design", "Digital Art and Design", "Digital Media"],
  ], {}, { subtitle: "Largest Credit Division Within Each School", notes: "Program groups are the largest credit-program division within each school." });

  // --- line 31: 1-FIGURE: Impact of TSTC on Earnings: Construction Certificate
  figSlide("Impact of TSTC on Earnings: Construction Certificate", "TSTC Enrollees who Graduate vs. Digital Twins -- $27K Increase", "cert_construction_graduate_event_study", { notes: "Strongest result in the deck. ROI 33.8x, payback 0.6 years." });

  // --- line 36: 1-FIGURE: Impact of TSTC on Earnings: Engineering Associate's Degree
  figSlide("Impact of TSTC on Earnings: Engineering Associate's Degree", "TSTC Enrollees who Graduate vs. Digital Twins -- $14K Increase", "aas_engineering_graduate_event_study", { notes: "ROI 8.4x on a cost of $14K." });

  // --- line 41: 1-FIGURE: Impact of TSTC on Earnings: Engineering Associate's Degree
  figSlide("Impact of TSTC on Earnings: Engineering Associate's Degree", "TSTC Enrollees who Leave vs. Digital Twins -- $2K Increase", "aas_engineering_leaver_event_study", { notes: "Leavers gain far less than graduates. The second dashed line marks expected completion, not an observed exit date." });

  // --- line 46: 1-FIGURE: Impact of TSTC on Earnings: Automotive Associate's Degree
  figSlide("Impact of TSTC on Earnings: Automotive Associate's Degree", "TSTC Enrollees who Graduate vs. Digital Twins -- $7K Increase", "aas_automotive_graduate_event_study", { notes: "CIP 47 is Mechanic and Repair Technologies and includes aviation and diesel, so the cost shown is above the automotive programs themselves." });

  // --- line 51: 1-FIGURE: Impact of TSTC on Earnings: Automotive Certificate
  figSlide("Impact of TSTC on Earnings: Automotive Certificate", "TSTC Enrollees who Graduate vs. Digital Twins -- $9K Increase", "cert_automotive_graduate_event_study", { notes: "Certificates complete in 12 months, so the second dashed line sits at year 1." });

  // --- line 56: 1-FIGURE: Impact of TSTC on Earnings: IT Associate's Degree
  figSlide("Impact of TSTC on Earnings: IT Associate's Degree", "TSTC Enrollees who Graduate vs. Digital Twins -- $890 Increase", "aas_it_graduate_event_study", { notes: "Weakest result. $890 does not break even -- ROI 0.7x, payback 30.2 years." });

  // --- line 61: TEXT: Appendix
  deck.addRichTextSlide("Appendix", [
    "Estimates use the September 2026 disclosure, statistic `mean`.",
    "The digital twins counterfactual is released for years 0-5 only; the pre-period is filled with the treated series plus uniform jitter.",
    ["Flagged in the data as `imputed_control_aipw` (small)", 1],
    "ROI assumes a 0.4 graduation rate over 20 years.",
  ]);

  // --- line 67: 1-FIGURE: Impact of TSTC on Earnings: Engineering Associate's Degree
  figSlide("Impact of TSTC on Earnings: Engineering Associate's Degree", "TSTC Enrollees who Graduate vs. Leave vs. Digital Twins", "aas_engineering_combined_event_study", { notes: "Graduates and leavers on one axis. Replaces the hand-built slide whose subtitle said \"Enrollees who Leave\" under a chart showing both." });

  await deck.save();
  report();
}

const fs2 = require("fs");
const DRAFT = process.argv.includes("--draft");
let planned = 0;
const skipped = [];
const have = (name) =>
  fs2.existsSync(path.join(FIG_DIR, name + ".svg")) ||
  fs2.existsSync(path.join(FIG_DIR, name + ".png"));
function guard(names) {
  planned += 1;
  const missing = names.filter((n) => n && !have(n));
  if (!missing.length) return true;
  if (!DRAFT) {
    console.error(`\nMissing figure(s) on slide ${planned}: ${missing.join(", ")}`);
    console.error("Run the figures step first, or pass --draft to skip.");
    process.exit(1);
  }
  skipped.push({ n: planned, names: missing });
  return false;
}
function figSlide(t, s, name, opts) {
  if (guard([name])) deck.addFigureSlide(t, s, fig(name), opts);
}
function multiFigSlide(t, s, names, cols, rows, panelTitles, opts) {
  if (guard(names))
    deck.addMultiFigureSlide(t, s, names.map(fig), cols, rows, Object.assign({ panelTitles }, opts));
}
function threeFigSlide(t, s, names, panelTitles, opts) {
  if (guard(names)) deck.add3FigureSlide(t, s, names.map(fig), panelTitles, opts);
}
function report() {
  if (skipped.length)
    console.warn(`\n  skipped ${skipped.length} slide(s) with missing figures: ` +
      skipped.map((s) => `#${s.n} ${s.names.join(",")}`).join("; "));
}

main().catch((e) => { console.error("Build failed:", e); process.exit(1); });
